import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Header } from "@/components/Header";
import Image from "next/image";
import bg from "../../public/bg2.jpg";
import "./globals.css";

const font = Poppins({ weight: ["400", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="overflow-hidden">
          <Image
            src={bg}
            alt=""
            className="fixed top-0 bottom-0 left-0 right-0 object-cover"
          />
          <main className="w-full h-[100vh] relative flex overflow-hidden">
            <Header />
            <div className="bg-black/80 h-[calc(100vh-1.25rem)] w-full p-[3rem] rounded-3xl m-3 overflow-y-scroll no-scrollbar">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
